/* eslint-disable import/no-unassigned-import */
import './color.js'
import './completers.js'
import './configuration.js'
import './configuration-default.js'
import './configuration-plugins.js'
import './configuration-presets.js'
import './configuration-transform.js'
import './core.js'
import './file-path.js'
import './ignore.js'
import './input.js'
import './inspect.js'
import './output.js'
import './reporting.js'
import './settings-and-plugins.js'
import './stdin.js'
import './tree.js'
/* eslint-enable import/no-unassigned-import */
